# Generated by Django 4.2.3 on 2023-07-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rating', models.PositiveIntegerField()),
                ('abv', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
