# Generated by Django 4.2.3 on 2023-07-13 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("rating", models.PositiveIntegerField()),
                ("abv", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "autos_table",
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "coche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventas",
                        to="auto_app.coche",
                    ),
                ),
            ],
            options={
                "db_table": "ventas_table",
            },
        ),
    ]
